apiVersion: v1
kind: Service
metadata:
  name: lb-service
  namespace: {{ .Values.namespace }}
  labels:
    app: lb-service
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
  selector:
    app: {{ .Chart.Name }}
