apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: static-app
  name: static-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: static-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: static-app
    spec:
      containers:
      - image: nameson/devops-project-app:v3.0
        name: static-app
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: static-app