replicaCount: 3

image:
  repository: nameson/devops-project-app
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: LoadBalancer
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
