apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: static-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/nameson2672/k8-cluster'
    targetRevision: HEAD
    path: devops-app
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
