apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: devops-tools
spec:
  project: default
  source:
    repoURL: 'https://github.com/nameson2672/k8-cluster'
    targetRevision: HEAD
    path: jenkins
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: devops-tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
